### PR TITLE
Add `FFmpegControllerBuilder` class

### PR DESCRIPTION
**Pull request by andcscott**
Partially addresses #4 and progresses #31 with the need for a separate `FFmpegControllerBuilder` as identified in #28 

I hope it's alright that I'm choosing to address this piecemeal. The motivation is partially selfish in that I'm participating in Hacktoberfest, but it was also a little difficult to wrap my head around at first. Since `FFmpegController` and `FFmpegCommandBuilder` will likely depend on the implementation of this class I thought it was a better place to start than last time. 

This patch provides an adapted version of the `FFmpegController` submitted for #28 as `FFmpegControllerBuilder`. It contains the configuration options needed by `FFmpegController` with the structs we discussed.

You can see my current progress on `FFmpegController` at andcscott/fast-music-remover@d11e7ff, although in the absence of a `FFmpegCommandBuilder` I've been using the existing `CommandBuilder` to familiarize myself. In any case, I'll continue using the #31 branch as we iterate through any needed changes for all three classes to keep things tidy, unless you prefer something else.

### CODE REVIEW

**Comment by omeryusufyagci** [comment]
Thanks for this @andcscott! I checked, and the building part looks good. What I don't like so much here is that the builder is also managing the configuration of ffmpeg. Ideally the builder shouldn't have getters, and it should exclusively _build._

I think the best way to properly handle all these is to introduce an `FFmpegConfigManager`, similar to the `ConfigManager` we have -probably not a singleton for this one though. 

Here's what I have in mind:
```cpp
FFmpegConfigManager configManager;
configManager.setAudioCodec("aac");
// others...

FFmpegController controller(configManager);

controller.extractAudio();
```
and inside the `FFmpegController` we'll directly utilize this builder you're writing:
```cpp
void extractAudio() {
    FFmpegControllerBuilder builder;
    builder.setAudioCodec(configManager.getAudioCodec())
    builder.setXXX // other settings

    runCommand(builder.build());
}
```

As you see, once we have everything in place, it becomes quite convenient to design the high level API. So, I think in the end this will be very pleasant to work with, but some more work to be done to get there. 

Coming back to this PR, we should remove the getters and config management from the builder and let it focus exclusively on building.

This now will require a the `FFmpegConfigManager` to work, and I can help you with that or any other part of this multi-leg feature bundle. Just let me know. It might not come super fast, but I'll try my best! I have some ongoing work on the filtering end I want to push, but couldn't get around to it just yet. 

Btw, sorry about the hacktoberfest, I forgot about it. I'm already marking this as accepted as your contributions clearly satisfy the rules, and please let me know if I missed any other PRs, and I'll mark them accepted as well.

We could open a discussion dedicated to all of this iron out the details if you wish. We've discussed quite a few things, and I'm happy to go over them again. Thanks !

**Comment by andcscott** [comment]
At this point a discussion might be helpful. I do see what you mean about the "builder" not having getters, I think where I'm getting confused is how everything comes together. So far we've talked about:

- FFmegController
- FFmegControllerBuilder
- FFmpegCommandBuilder
- FFmpegConfigManager

While I'm confident in my ability to write the actual code, having to keep track of all that in separate issues and PRs is becoming a lot (and hopefully I haven't missed any).

Don't stress too much about hacktoberfest either. While I'd like for all of my qualifying PRs to count I'm not taking it incredibly seriously, and I totally understand that you have other things to do. I got caught up myself this week so it's no problem at all.

**Comment by omeryusufyagci** [comment]
Hey @andcscott ,

I totally understand it wasn't easy to keep the context through multiple issues and PRs, and it would've been much better if we had a design doc for this! That'd be too easy though, wouldn't it! :) 

Don't hesitate to start a discussion, but for completeness under this PR, here's how everything fits together:

- FFmpegConfigManager: This is the global configuration manager for paths and thread settings, acting as a single source of truth.

- FFmpegCommandBuilder: This guy builds individual FFmpeg commands, mainly an abstraction from the low-level string manipulations. Particularly useful for cross-platform compatability

- FFmpegControllerBuilder: This builds the controller with configurations from the FFmpegConfigManager and commands from FFmpegCommandBuilder.

- FFmpegController: This is our public API that orchestrates operations like `extractAudio()`, etc. This is what the user interacts with, while everything else happens under the hood.

This gives us the freedom to change how we construct the ffmpeg commands, which could come at some point to avoid the OS calls. The CommandBuilder helps us not make mistakes digging into string ops for changes, and we handle the ffmpeg related config with a dedicated ConfigManager. 

Does it sound better now? As I said, don't hesitate to start a page if you'd like! (maybe discord soon? !)

**Comment by omeryusufyagci** [comment]
@andcscott please also take a look at #44. I made a first implementation for the FFmpegSettingsManager. I decided to make this focused strictly on settings, and reuse ConfigManager for configurations.

**Comment by andcscott** [comment]
Ok cool, I should have time to go over those details tomorrow. I did end up starting #45 so we can continue the conversation outside issues and PRs. Your comment earlier today was very helpful, but with #44 in the works I guess I'm not sure what to work on next - several other pieces need to fall into place before I can fix this PR. Anyway, looking forward to continuing the discussion!

**Comment by andcscott** [comment]
Hi @omeryusufyagci, hope you're having an excellent Friday! Pushed some changes that will hopefully bring this PR in line with the rest of the project.

Only 3 commits this time:
1. Removed the input/output file vars from `FFmpegSettingsManager`. Other references to those vars were already removed in #51.
2. Added the header for `FFmpegController`. The final implementation will come down to how we progress on the current class,
3. Added `FFmpegControllerBuilder`. This new class will accept the settings for `FFmpegSettingsManager` and return a unique ptr to a `FFmpegController`. The intent is that ownership of all references will be transferred to the newly built Controller.

**Comment by omeryusufyagci** [comment]
> Hi @omeryusufyagci, hope you're having an excellent Friday! Pushed some changes that will hopefully bring this PR in line with the rest of the project.
> 
> Only 3 commits this time:
> 
> 1. Removed the input/output file vars from `FFmpegSettingsManager`. Other references to those vars were already removed in [Add `FFmpegCommandBuilder` class #51](https://github.com/omeryusufyagci/fast-music-remover/pull/51).
> 2. Added the header for `FFmpegController`. The final implementation will come down to how we progress on the current class,
> 3. Added `FFmpegControllerBuilder`. This new class will accept the settings for `FFmpegSettingsManager` and return a unique ptr to a `FFmpegController`. The intent is that ownership of all references will be transferred to the newly built Controller.

Hi @andcscott, thanks, busy as usual but all is well : ) I hope you're having a nice weekend too!

I just merged your last PR to main and consequently deleted the dedicated branch. Since this PR was also targeting the same branch, it got automatically closed. I can't reopen it as the branch no longer exist. 

Could you please target this PR to the new branch I opened via #58? You should be able to reopen then, but if you can't let me know and I'll open it. Thanks!

**Comment by andcscott** [comment]
Glad to hear it, all good on my end too! And it's no problem, github is apparently pretty insistent that neither of us reopen this one haha so I just opened #59

**Pull request closed without merging**
